name: ci

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: lunarmodules/luacheck@v0

  testing:
    strategy:
      matrix:
        nvim-version: ["v0.6.0", "v0.6.1", "v0.7.0", "nightly"]
      # If one versions fails, still run all the other versions
      fail-fast: false
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Install Neovim ${{ matrix.nvim-version }}
        run: |
          mkdir ./neovim
          curl -sL https://github.com/neovim/neovim/releases/download/${{ matrix.nvim-version }}/nvim-linux64.tar.gz \
            | tar xzf - --strip-components=1 -C ./neovim
          ./neovim/bin/nvim --version

      - name: Install Just
        uses: extractions/setup-just@v1

      - name: Run tests
        run: |
          export PATH="./neovim/bin:$PATH"
          export VIM="./neovim/share/nvim/runtime"
          just test
