name: default

on: [push, pull_request]

jobs:
  testing:
    strategy:
      matrix:
        nvim-version: ["v0.5.0", "v0.5.1", "v0.6.0", "v0.6.1", "nightly"]
      # If one versions fails, still run all the other versions
      fail-fast: false
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Neovim ${{ matrix.nvim-version }}
        run: |
          mkdir ./neovim
          curl -sL https://github.com/neovim/neovim/releases/download/${{ matrix.nvim-version }}/nvim-linux64.tar.gz \
            | tar xzf - --strip-components=1 -C ./neovim

      - name: Run tests
        run: |
          export PATH="./neovim/bin:$PATH"
          export VIM="./neovim/share/nvim/runtime"
          make test
